CREATE TABLE HOLIDAYS
(
    ID            NUMBER PRIMARY KEY,
    HOLIDAY_DATE  DATE
);

CREATE SEQUENCE holidays_seq START WITH 1;

CREATE TABLE USERS
(
    ID          NUMBER PRIMARY KEY,
    LOGIN       VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(120) NOT NULL UNIQUE
);

CREATE SEQUENCE users_seq START WITH 1;